---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  MOVIE_FUN_URL:

inputs:
- name: apps-movie-fun-code-spring-boot

run:
  path: apps-movie-fun-code-spring-boot/ci/tasks/smoke-test.sh
